---
- name: Download cfssl binaries
  get_url:
    url: "https://github.com/cloudflare/cfssl/releases/download/v{{ k8s_cert_cfssl_version }}/{{ item }}_{{ k8s_cert_cfssl_version }}_{{ k8s_cert_cfssl_os }}_{{ k8s_cert_cfssl_arch }}"
    dest: "{{ k8s_cert_cfssl_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    checksum: "sha256:{{ k8s_cert_cfssl_checksum_url }}"
  with_items:
    - cfssl
    - cfssl-bundle
    - cfssl-certinfo
    - cfssl-newkey
    - cfssl-scan
    - cfssljson
    - mkbundle
    - multirootca